In [0]:
from __future__ import print_function
import torch

# Tensors

In [2]:
x = torch.empty(5, 3)

print(x)

tensor([[1.7191e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)

print(x)

tensor([[0.0326, 0.4974, 0.8353],
        [0.7340, 0.6347, 0.3311],
        [0.0056, 0.3293, 0.0462],
        [0.0281, 0.7541, 0.9336],
        [0.5849, 0.1814, 0.5395]])


In [4]:
x = torch.zeros(5, 3, dtype = torch.long)

print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])

print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1465,  0.6501,  1.4130],
        [ 0.7883,  1.9018, -2.5592],
        [-1.2009,  0.7214, -0.9734],
        [-1.5392, -0.1012, -0.2325],
        [-0.1215, -0.5672,  1.0818]])


In [7]:
print(x.size())

torch.Size([5, 3])


# Operations

In [8]:
y = torch.rand(5,3)
x = torch.rand(5,3)
z = x+y
print(z)

tensor([[1.2762, 1.2608, 1.7661],
        [1.0114, 0.4650, 0.8981],
        [0.7981, 1.3313, 1.9112],
        [1.4461, 0.3053, 0.5846],
        [1.6530, 1.3625, 0.2528]])


In [9]:
z = torch.add(x, y)
print(z)

tensor([[1.2762, 1.2608, 1.7661],
        [1.0114, 0.4650, 0.8981],
        [0.7981, 1.3313, 1.9112],
        [1.4461, 0.3053, 0.5846],
        [1.6530, 1.3625, 0.2528]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[1.2762, 1.2608, 1.7661],
        [1.0114, 0.4650, 0.8981],
        [0.7981, 1.3313, 1.9112],
        [1.4461, 0.3053, 0.5846],
        [1.6530, 1.3625, 0.2528]])


In [11]:
y.add_(x)
print(y)

tensor([[1.2762, 1.2608, 1.7661],
        [1.0114, 0.4650, 0.8981],
        [0.7981, 1.3313, 1.9112],
        [1.4461, 0.3053, 0.5846],
        [1.6530, 1.3625, 0.2528]])


In [12]:
print(x[:1])

tensor([[0.7358, 0.6178, 0.8345]])


In [13]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0818])
1.0817595720291138


# NumPy Bridge

## Converting from Tensor to NumPy

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


## Converting from NumPy to Tensor

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## Move Tensor in and out of GPU (CUDA Tensor)

In [19]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.0818], device='cuda:0')
tensor([2.0818], dtype=torch.float64)
